# Generated by Django 3.0.1 on 2022-11-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Informacion_de_todos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('fecha_de_nacimiento', models.DateField(max_length=40)),
                ('años', models.IntegerField()),
            ],
        ),
    ]
