# Generated by Django 3.0.1 on 2022-11-03 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Info',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.CharField(max_length=40)),
                ('lugar_de_nacimiento', models.IntegerField()),
                ('hora_de_nacimiento', models.IntegerField()),
            ],
        ),
    ]
