# Generated by Django 3.0.1 on 2022-11-03 01:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hermana',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.CharField(max_length=40)),
                ('lugar_de_nacimiento', models.IntegerField()),
                ('hora_de_nacimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Madre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.CharField(max_length=40)),
                ('lugar_de_nacimiento', models.IntegerField()),
                ('hora_de_nacimiento', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Padre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_de_nacimiento', models.CharField(max_length=40)),
                ('lugar_de_nacimiento', models.IntegerField()),
                ('hora_de_nacimiento', models.IntegerField()),
            ],
        ),
        migrations.DeleteModel(
            name='Info',
        ),
    ]
