# Generated by Django 3.0.1 on 2022-11-07 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Familia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=40)),
                ('años', models.IntegerField()),
                ('fecha_de_nacimiento', models.DateField()),
            ],
        ),
        migrations.DeleteModel(
            name='Informacion_de_todos',
        ),
    ]
