# Generated by Django 3.0.1 on 2022-11-06 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='informacion_de_todos',
            name='fecha_de_nacimiento',
            field=models.DateField(),
        ),
    ]
