# Generated by Django 3.0.1 on 2022-11-03 15:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('App1', '0002_auto_20221103_0150'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hermana',
            old_name='hora_de_nacimiento',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='madre',
            old_name='hora_de_nacimiento',
            new_name='nacionalidad',
        ),
        migrations.RenameField(
            model_name='padre',
            old_name='hora_de_nacimiento',
            new_name='nacionalidad',
        ),
    ]
